import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";
import MicrosoftClarity from "@/metrics/MicrosoftClarity";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PixShop - Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col bg-white dark:bg-black md:overflow-hidden">
          <div className="w-full flex-none">
            <Navbar />
          </div>
          <div className="flex-grow ">{children}</div>
        </div>

        <MicrosoftClarity />
      </body>
    </html>
  );
}